FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "WARDEN: Hif fuff hefifoo!\p"
    .string "Ha lof ha feef ee hafahi ho.\n"
    .string "Heff hee fwee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "Ah howhee ho hoo!\n"
    .string "Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "Ha?\n"
    .string "He ohay heh ha hoo ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} gave the GOLD TEETH\n"
    .string "to the WARDEN.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "The WARDEN popped in his teeth!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "WARDEN: Thanks son!\n"
    .string "You're a real lifesaver!\p"
    .string "Let me give\n"
    .string "you something for\n"
    .string "your trouble.\p"
    .string "Also.\p"
    .string "Don't go near\n"
    .string "the west fence\n"
    .string "at night.\p"
    .string "I found my\n"
    .string "teeth there.\p"
    .string "I don't remember\n"
    .string "how they got there.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "WARDEN: Thank you, lassie!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the OFFICE, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} received HM04\n"
    .string "from the WARDEN.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "WARDEN: Inside HM04\n"
    .string "you'll find STRENGTH.\p"
    .string "Oh yes.\n"
    .string "Did you find\n"
    .string "the Secret House\n"
    .string "in the Safari Zone?\p"
    .string "Nullveil found it\n"
    .string "before you did.\p"
    .string "It's been using it.$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "Pokemon photos and\n"
    .string "fossils on display.\p"
    .string "One photo was\n"
    .string "taken at night.\p"
    .string "West fence.\n"
    .string "Something in frame.\p"
    .string "Warden keeps it\n"
    .string "face down.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "Old Pokemon merchandise\n"
    .string "on display.\p"
    .string "One item wasn't\n"
    .string "put here by\n"
    .string "the Warden.\p"
    .string "He doesn't know\n"
    .string "where it came from.\p"
    .string "It faces west.$"
