SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "Wait!\n"
    .string "Don't say a word.\p"
    .string "You wanted this.\p"
    .string "I knew you\n"
    .string "were coming.\p"
    .string "Chronyx knew first.\p"
    .string "It told me\n"
    .string "yesterday.\p"
    .string "Today hasn't happened yet\n"
    .string "for Chronyx.$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} received TM29\n"
    .string "from MR. PSYCHIC.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "You already know.\n"
    .string "TM29 is PSYCHIC.\p"
    .string "Attack that lowers\n"
    .string "special stats.\p"
    .string "My psychic power\n"
    .string "shows me things.\p"
    .string "I see Chronyx\n"
    .string "in this city.\p"
    .string "Time bends around it.\p"
    .string "I can't see\n"
    .string "past it.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"
