CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Nyaah!\p"
    .string "MEOWTH drops a\n"
    .string "stone with a\n"
    .string "mark on it.$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "You shouldn't spend all your money\n"
    .string "on drinks.\p"
    .string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "Nothing beats thirst like some hot\n"
    .string "TEA.\p"
    .string "It really is the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "Nothing beats thirst\n"
    .string "like some hot tea.\p"
    .string "My dear Pokemon\n"
    .string "keep me company.\n"
    .string "Meowth even brings\n"
    .string "money home.\p"
    .string "Meowth has been\n"
    .string "bringing something else\n"
    .string "home lately.\n"
    .string "Small stones.\p"
    .string "All with the\n"
    .string "same mark on them.\p"
    .string "I don't know\n"
    .string "where it finds them.$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "Oh, hello, dearie.\n"
    .string "Did you enjoy my TEA?\p"
    .string "By the way, dear. Are you, by any\n"
    .string "chance, from PALLET TOWN?\p"
    .string "A girl from PALLET TOWN, DAISY,\n"
    .string "she enjoys TEA every day.\p"
    .string "She visits the CELADON DEPT. STORE\n"
    .string "to buy some TEA.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON MANSION\n"
    .string "Manager's Suite$"

