PokemonTower_7F_Text_Grunt1Intro::
    .string "What do you want?\n"
    .string "Why are you here?\p"
    .string "We ask ourselves\n"
    .string "that too lately.$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "I give up.$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "I won't forget this.\p"
    .string "I won't forget\n"
    .string "what I saw\n"
    .string "in this tower either.$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "This old man came\n"
    .string "to our hideout\n"
    .string "ranting about Pokemon.\p"
    .string "We brought him here\n"
    .string "to talk it over.\p"
    .string "The tower had\n"
    .string "other ideas.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "No more.$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "Pokemon are for\n"
    .string "making money.\p"
    .string "That's what I\n"
    .string "told myself before\n"
    .string "I came here.$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "You're not saving anyone.\p"
    .string "Neither are we\n"
    .string "anymore.$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "Don't fight us.$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "You're not getting\n"
    .string "away with this.\p"
    .string "Neither are we.$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "MR. FUJI: Heh?\n"
    .string "You came to save me?\p"
    .string "Thank you. But, I came here of my\n"
    .string "own free will.\p"
    .string "I came to calm the spirit of\n"
    .string "CUBONE's mother.\p"
    .string "I think MAROWAK's spirit has\n"
    .string "finally left us.\p"
    .string "I must thank you for your kind\n"
    .string "concern.\p"
    .string "Follow me to my home, POKéMON\n"
    .string "HOUSE, at the foot of this tower.$"
