VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "I'm getting my\n"
    .string "Pidgey to fly\n"
    .string "a letter to Saffron.\p"
    .string "Pidgey was nervous\n"
    .string "this morning.\p"
    .string "Wouldn't leave at first.\p"
    .string "Kept circling the\n"
    .string "roof.\n"
    .string "Looking at something.$"

VermilionCity_House3_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!\p"
    .string "PIDGEY eyes the sky.$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear PIPPI.\n"
    .string "I hope to\n"
    .string "see you soon.\p"
    .string "Saffron has problems\n"
    .string "with Team Rocket.\p"
    .string "Vermilion appears safe.\p"
    .string "The harbor is\n"
    .string "less safe at night.\p"
    .string "Don't tell anyone.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "I send my\n"
    .string "Pidgey to the\n"
    .string "Union Room for mail.\p"
    .string "My Pidgey came\n"
    .string "back last week\n"
    .string "with singed feathers.\p"
    .string "I didn't send\n"
    .string "it near anything hot.$"

