SafariZone_Center_Text_RestHouse::
    .string "REST HOUSE\p"
    .string "Something rests here\n"
    .string "that isn't tired.$"

SafariZone_Center_Text_PressStartToCheckTime::
    .string "Time passes differently\n"
    .string "inside the Zone.\p"
    .string "Check your remaining time.\p"
    .string "It may not match\n"
    .string "your watch.$"

SafariZone_Center_Text_CenterArea::
    .string "CENTER AREA\p"
    .string "Something watches\n"
    .string "from the center.$"

