SafariZone_West_Text_RestHouse::
    .string "REST HOUSE\p"
    .string "Something tried to\n"
    .string "enter last night.\p"
    .string "We didn't open.$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "REQUEST NOTICE\p"
    .string "The Safari Warden\n"
    .string "lost his Gold Teeth.\p"
    .string "They're around here somewhere.\p"
    .string "He's been looking\n"
    .string "for three weeks.\p"
    .string "The Zone won't\n"
    .string "let him find them.$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "AREA 3\p"
    .string "Something in this\n"
    .string "zone has been\n"
    .string "here longer than\n"
    .string "the Eryn Vorn itself.$"

SafariZone_West_Text_AreaSign::
    .string "AREA 3\n"
    .string "EAST: CENTER AREA\p"
    .string "Don't go east\n"
    .string "after dark.$"

