PokemonTower_4F_Text_PaulaIntro::
    .string "Ghost! No! Kwaaah!\p"
    .string "I don't know\n"
    .string "if I'm seeing\n"
    .string "it or being it.$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "Where is the ghost?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "I must have\n"
    .string "been dreaming.\p"
    .string "We all are.$"

PokemonTower_4F_Text_LaurelIntro::
    .string "Be cursed with me.\p"
    .string "I was cursed\n"
    .string "before I came here.\p"
    .string "This place found\n"
    .string "what was already there.$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "What!$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "We cannot identify\n"
    .string "the spirits.\p"
    .string "They cannot identify\n"
    .string "themselves.$"

PokemonTower_4F_Text_JodyIntro::
    .string "Huhuhu... Beat me not.\p"
    .string "I'm not sure\n"
    .string "who's asking.$"

PokemonTower_4F_Text_JodyDefeat::
    .string "Who? What?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "May the departed\n"
    .string "rest in peace.\p"
    .string "May we also.$"
