CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "Super Repel keeps\n"
    .string "weak Pokemon away.\n"
    .string "More powerful than Repel.\p"
    .string "Nothing repels ProtoGlyph.\p"
    .string "It moves through\n"
    .string "walls if it\n"
    .string "wants to.\p"
    .string "Repel is irrelevant.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "For long outings\n"
    .string "buy Revive.\p"
    .string "Also buy something\n"
    .string "for your nerves.\p"
    .string "ProtoGlyph has been\n"
    .string "seen on the\n"
    .string "route south.\p"
    .string "Long outings are\n"
    .string "riskier now.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "Top-Grade Items for TRAINERS!\p"
    .string "2F: TRAINER'S MARKET$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "We have a\n"
    .string "customer named Lance.\n"
    .string "Always buys capes.\p"
    .string "He came in\n"
    .string "last week.\n"
    .string "Very pale.\p"
    .string "Asked if we\n"
    .string "sell anything that\n"
    .string "repels stone entities.\p"
    .string "We don't.$"
