Text_OnlySkilledTrainersAllowedThrough::
	.string "Only those who\n"
	.string "have proven themselves\p"
	.string "may pass.\p"
	.string "You don't have\n"
	.string "the {STR_VAR_1} yet.$"

Text_CantLetYouPass::
	.string "I cannot let\n"
	.string "you through.\p"
	.string "Something on the\n"
	.string "other side is\p"
	.string "waiting for you.\p"
	.string "You're not ready.$"

Text_OhThatsBadgeGoRightAhead::
	.string "The {STR_VAR_1}.\p"
	.string "You earned this.\p"
	.string "Go through.\p"
	.string "Something is waiting\n"
	.string "for you.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "You can pass here only if you have\n"
	.string "the {STR_VAR_1}.\p"
	.string "You don't have the {STR_VAR_1}\n"
	.string "yet.\p"
	.string "You have to have it to get to\n"
	.string "the POKéMON LEAGUE.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "You can pass here only if you have\n"
	.string "the {STR_VAR_1}.\p"
	.string "Oh! That is the {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Okay, then.\n"
	.string "Please, go right ahead.$"
