PokemonTower_6F_Text_AngelicaIntro::
    .string "Give me blood.\p"
    .string "I don't know\n"
    .string "why I said that.\p"
    .string "Something does.$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "Groan.$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "I feel weak.\p"
    .string "Like something took\n"
    .string "more than the battle.$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Urff... Kwaah!\p"
    .string "Something fell into me\n"
    .string "coming up the stairs.$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "Something fell out.$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "My hair is fine.\p"
    .string "A malevolent spirit\n"
    .string "used me.\p"
    .string "I felt it thinking.$"

PokemonTower_6F_Text_JenniferIntro::
    .string "Ke ke ke ke\n"
    .string "ke ke!\p"
    .string "That's not me.$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "Keee.$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "What's happening here?\p"
    .string "Something uses us\n"
    .string "as instruments.$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Be gone... Intruders...\p"
    .string "This is not\n"
    .string "your grief.$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "The ghost was\n"
    .string "Cubone's mother.\p"
    .string "She didn't know\n"
    .string "she was gone.$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "The mother's spirit\n"
    .string "is calm.\p"
    .string "She has left.\p"
    .string "Something else\n"
    .string "has not.$"
