VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .string "Team Rocket traffics\n"
    .string "in rare Pokemon.\p"
    .string "They abandon ones\n"
    .string "they find useless.\p"
    .string "A Rocket grunt\n"
    .string "arrived here last\n"
    .string "week.\n"
    .string "Very pale.\p"
    .string "He said something\n"
    .string "followed their ship\n"
    .string "from Sevii.\p"
    .string "He quit Team Rocket.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .string "Pokemon can be\n"
    .string "good or bad.\p"
    .string "Depends on the\n"
    .string "Trainer.\p"
    .string "Something has been\n"
    .string "here with no\n"
    .string "Trainer at all.\p"
    .string "It didn't need one.$"

