Text_RockSlideTeach::
    .string "Rockslides are a\n"
    .string "threat up here.\p"
    .string "Something else is\n"
    .string "also a threat.\p"
    .string "At least rockslides\n"
    .string "you can see coming.\p"
    .string "Want to learn\n"
    .string "Rock Slide?$"

Text_RockSlideDeclined::
    .string "Come back if\n"
    .string "you change your mind.\p"
    .string "I'll be here.\p"
    .string "I'm not leaving\n"
    .string "this tunnel alone.$"

Text_RockSlideWhichMon::
    .string "Which POKéMON should I teach\n"
    .string "ROCK SLIDE?$"

Text_RockSlideTaught::
    .string "Use it wisely.\p"
    .string "In here especially.$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .string "Hint: Boulders might change the\n"
    .string "flow of water.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .string "DANGER\n"
    .string "Fast current!$"

