SaffronCity_Mart_Text_MaxRepelMoreEffectiveThanSuper::
    .string "MAX REPEL keeps\n"
    .string "weaker Pokemon away.\n"
    .string "Lasts longer than\n"
    .string "SUPER REPEL.\p"
    .string "Nothing repels Chronyx.\p"
    .string "It doesn't respond\n"
    .string "to smell.$"

SaffronCity_Mart_Text_ReviveIsCostly::
    .string "REVIVE is costly\n"
    .string "but revives fainted Pokemon.\p"
    .string "Can't revive lost time.\p"
    .string "Chronyx took an\n"
    .string "hour from this\n"
    .string "mart last Wednesday.\n"
    .string "The clerk didn't\n"
    .string "notice until Thursday.$"
