SafariZone_North_Text_RestHouse::
    .string "REST HOUSE\p"
    .string "Don't stay long.$"

SafariZone_North_Text_SecretHouseStillAhead::
    .string "The Secret House\n"
    .string "is still ahead.\p"
    .string "So is something else.$"

SafariZone_North_Text_Area2::
    .string "AREA 2\p"
    .string "The tall grass\n"
    .string "moves before you\n"
    .string "enter it.$"

SafariZone_North_Text_ZigzagThroughTallGrass::
    .string "Pokemon hide in\n"
    .string "tall grass.\p"
    .string "Other things hide\n"
    .string "in the tall grass too.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .string "Find the Secret House.\p"
    .string "What you find\n"
    .string "inside is not\n"
    .string "always what you\n"
    .string "expect.$"

