SafariZone_East_Text_RestHouse::
    .string "REST HOUSE\p"
    .string "You are not\n"
    .string "alone in here.$"

SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk::
    .string "Time passes only\n"
    .string "while you walk.\p"
    .string "Something in here\n"
    .string "moves when you stop.$"

SafariZone_East_Text_AreaSign::
    .string "AREA 1\p"
    .string "WEST: CENTER AREA\p"
    .string "The Zone is\n"
    .string "larger than the\n"
    .string "maps suggest.$"

