Route18_EastEntrance_1F_Text_NeedBicycleForCyclingRoad::
    .string "You need a bicycle\n"
    .string "for Cycling Road.\p"
    .string "Whatever is on\n"
    .string "that road doesn't.$"

Route18_EastEntrance_1F_Text_CyclingRoadAllUphillFromHere::
    .string "Cycling Road is\n"
    .string "all uphill from here.\p"
    .string "The downhill side\n"
    .string "takes longer than\p"
    .string "it should.$"

Route18_EastEntrance_1F_Text_ExcuseMe::
    .string "Excuse me.\p"
    .string "Don't stop moving\n"
    .string "on that road.$"

