Nebelsteg_Text_Fischer:
    .string "Das Meer flüstert\n"
    .string "seit jener Nacht.\p"
    .string "Etwas zieht durch\n"
    .string "den Nebel. Altes.\p"
    .string "Ich fische nicht\n"
    .string "mehr nach Einbruch\l"
    .string "der Dunkelheit.$"

Nebelsteg_Text_Kind:
    .string "Mama sagt, ich soll\n"
    .string "nicht ans Wasser.\p"
    .string "Aber nachts höre\n"
    .string "ich Flügelschlagen\p"
    .string "im Nebel...$"
