Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "Hiya! I'm BILL!\p"
    .string "I'm a POKéMANIAC\n"
    .string "and I made\p"
    .string "a terrible mistake.\p"
    .string "I got combined\n"
    .string "with a POKéMON\p"
    .string "during an experiment.\p"
    .string "Help me out here.\p"
    .string "Please.$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "Hiya! I'm BILL!\p"
    .string "I'm a POKéMANIAC\n"
    .string "and I made\p"
    .string "a terrible mistake.\p"
    .string "I got combined\n"
    .string "with a POKéMON\p"
    .string "during an experiment.\p"
    .string "Help me out here.\p"
    .string "Please.$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "Wait till I get inside the\n"
    .string "TELEPORTER.\p"
    .string "When I do, go to my PC and run\n"
    .string "the Cell Separation System.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "Come on.\p"
    .string "I can't stay\n"
    .string "like this.\p"
    .string "Please.\p"
    .string "I'm running out\n"
    .string "of time.$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "Come on.\p"
    .string "I can't stay\n"
    .string "like this.\p"
    .string "Please.\p"
    .string "I'm running out\n"
    .string "of time.$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: Thank you.\p"
    .string "BILL: I owe you.\p"
    .string "BILL: Take this.\p"
    .string "BILL: Go to VERMILION.\p"
    .string "BILL: The S.S. ANNE\n"
    .string "is there.\p"
    .string "BILL: Get away from\n"
    .string "this cape for a while.\p"
    .string "BILL: I need to\n"
    .string "think.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: Thank you.\p"
    .string "BILL: I owe you.\p"
    .string "BILL: Take this.\p"
    .string "BILL: Go to VERMILION.\p"
    .string "BILL: The S.S. ANNE\n"
    .string "is there.\p"
    .string "BILL: Get away from\n"
    .string "this cape for a while.\p"
    .string "BILL: I need to\n"
    .string "think.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} received an S.S. TICKET\n"
    .string "from BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "You've got too much stuff!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "The S.S. ANNE\n"
    .string "is in VERMILION.\p"
    .string "They invited me.\p"
    .string "I can't leave\n"
    .string "right now.\p"
    .string "Something in the\n"
    .string "water needs watching.\p"
    .string "You go instead.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Feel like seeing\n"
    .string "my collection?\p"
    .string "BILL: Some of it\n"
    .string "I can't explain.\p"
    .string "BILL: Go ahead.\n"
    .string "Check the PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "TELEPORTER is displayed on the PC\n"
    .string "monitor.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} initiated the TELEPORTER's\n"
    .string "Cell Separator.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "BILL's favorite POKéMON list!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Which POKéMON do you want to see?$"

