Route5_SouthEntrance_Text_ThirstyOnGuardDuty::
    .string "The road is closed.\p"
    .string "I've been standing here\n"
    .string "so long I forgot why.$"

Route5_SouthEntrance_Text_ThatTeaLooksTasty::
    .string "Oh, that TEA…\n"
    .string "It looks awfully tasty…$"

Route5_SouthEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "Huh? I can have this drink?\n"
    .string "Gee, thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this TEA with the other\n"
    .string "guards!$"

Route5_SouthEntrance_Text_HiHowsItGoing::
    .string "Something came through\n"
    .string "here last night.\p"
    .string "I didn't see what it was.\p"
    .string "Just keep moving.$"

