FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Uh.\n"
    .string "Oh yes.\n"
    .string "I'm the MOVE DELETER.\p"
    .string "I can make\n"
    .string "Pokemon forget moves.\p"
    .string "Would you like\n"
    .string "me to do that?\p"
    .string "Nullveil forgets nothing.\p"
    .string "That's the problem.$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Which POKéMON should forget a\n"
    .string "move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Come again if\n"
    .string "there are other\n"
    .string "moves to be forgotten.\p"
    .string "Some things can't\n"
    .string "forget what they've seen.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "What?\n"
    .string "No EGG should know any moves.$"
