PokemonTower_3F_Text_HopeIntro::
    .string "Urrg... Awaa...\n"
    .string "Huhu... Graa...$"

PokemonTower_3F_Text_HopeDefeat::
    .string "I'm saved.$"

PokemonTower_3F_Text_HopePostBattle::
    .string "The Silph Scope\n"
    .string "identifies ghosts.\p"
    .string "Some things here\n"
    .string "aren't ghosts.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "Kekeke... Kwaaah!\p"
    .string "I don't know\n"
    .string "if that's me.$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "What am I doing?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "I was possessed.\p"
    .string "I think.$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "Be gone malevolent spirit!\p"
    .string "I can't tell\n"
    .string "which of us\n"
    .string "it's in.$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "The spirit left.$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "The ones above\n"
    .string "must have been\n"
    .string "possessed longer.\p"
    .string "They've forgotten they were.$"
