@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "Nebelruf is\n"
    .string "just ahead.\p"
    .string "The Name Rater there\n"
    .string "changed his own name.\p"
    .string "He won't say\n"
    .string "what to.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "Felsmorn is\n"
    .string "pitch black inside.\p"
    .string "But some people say\n"
    .string "they could see fine.\p"
    .string "They won't describe\n"
    .string "what they saw.$"

