.include "data/maps/Nebelsteg_Verlasseneshaus/text.inc"

Nebelsteg_Verlasseneshaus_MapScripts::
	.byte 0

Nebelsteg_Verlasseneshaus_EventScript_Notiz1::
    msgbox Nebelsteg_Verlasseneshaus_Text_Notiz1, MSGBOX_SIGN
    end

Nebelsteg_Verlasseneshaus_EventScript_Notiz2::
    msgbox Nebelsteg_Verlasseneshaus_Text_Notiz2, MSGBOX_SIGN
    end

Nebelsteg_Verlasseneshaus_EventScript_Notiz3::
    msgbox Nebelsteg_Verlasseneshaus_Text_Notiz3, MSGBOX_SIGN
    end
