Nebelsteg_Verlasseneshaus_Text_Notiz1:
    .string "Tagebuch - 3. Tag\n"
    .string "des Nebelmonats\p"
    .string "Aeralith war wieder\n"
    .string "da. Größer als\p"
    .string "der Leuchtturm.\n"
    .string "Es hat uns gesehen.$"

Nebelsteg_Verlasseneshaus_Text_Notiz2:
    .string "Die Wächter kehren\n"
    .string "zurück. Vier an\p"
    .string "der Zahl. Erde,\n"
    .string "Himmel, Leere\p"
    .string "und Zeit. Was\n"
    .string "weckt sie auf?$"

Nebelsteg_Verlasseneshaus_Text_Notiz3:
    .string "Verlass diese\n"
    .string "Stadt. Heute\p"
    .string "noch.$"
