PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "Come child.\p"
    .string "I have purified\n"
    .string "this space.\p"
    .string "Rest here.\p"
    .string "It will not\n"
    .string "stay purified long.$"

PokemonTower_5F_Text_TammyIntro::
    .string "Give me your all.\p"
    .string "Something already\n"
    .string "took most of mine.$"

PokemonTower_5F_Text_TammyDefeat::
    .string "Gasp.$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "I was under\n"
    .string "possession.\p"
    .string "I'm not sure\n"
    .string "it's finished.$"

PokemonTower_5F_Text_RuthIntro::
    .string "You shall join us.\p"
    .string "All who come\n"
    .string "here long enough\n"
    .string "join us.$"

PokemonTower_5F_Text_RuthDefeat::
    .string "What a nightmare.$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "I was possessed.\p"
    .string "I still feel\n"
    .string "it nearby.$"

PokemonTower_5F_Text_KarinaIntro::
    .string "Zombies!\p"
    .string "I said that\n"
    .string "before I knew\n"
    .string "what I meant.$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "Ha?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "I regained my senses.\p"
    .string "For now.$"

PokemonTower_5F_Text_JanaeIntro::
    .string "Urgah... Urff...\p"
    .string "I trained in\n"
    .string "the mountains for this.\p"
    .string "It wasn't enough.$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "Whoo.$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "Evil spirits overcame\n"
    .string "my training.\p"
    .string "Some things cannot\n"
    .string "be trained against.$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "Entered the purified and protected\n"
    .string "zone.\p"
    .string "{PLAYER}'s POKéMON were fully\n"
    .string "healed.$"
