SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "Hi!\n"
    .string "Do you like Pokemon?\p"
    .string "I've been practicing\n"
    .string "mimicking something new.\p"
    .string "It doesn't speak.\p"
    .string "It doesn't move.\p"
    .string "It just changes\n"
    .string "how long things take.\p"
    .string "I can almost do it.$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "Hi!\n"
    .string "Do you like Pokemon?\p"
    .string "I've been practicing\n"
    .string "mimicking something new.\p"
    .string "It doesn't speak.\p"
    .string "It doesn't move.\p"
    .string "It just changes\n"
    .string "how long things take.\p"
    .string "I can almost do it.$"

Text_MimicTeach::
    .string "Oh wow!\n"
    .string "A POKé DOLL!\p"
    .string "For me?\n"
    .string "Thank you!\p"
    .string "You know what?\n"
    .string "I can teach the move MIMIC.$"

Text_MimicDeclined::
    .string "Don't you like MIMIC?$"

Text_MimicWhichMon::
    .string "I really love MIMIC!\n"
    .string "Who's going to learn it?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for earlier!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "DODUO: Giiih!\p"
    .string "PRETTY MIRROR LOOK AT ME.\n"
    .string "SEE HOW PRETTY I CAN BE.\p"
    .string "I SAID THIS\n"
    .string "ALREADY.\n"
    .string "DIDN'T I?\p"
    .string "I DON'T REMEMBER.$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "This is a\n"
    .string "rare Pokemon!\p"
    .string "Huh?\n"
    .string "It's only a doll.\p"
    .string "It was on\n"
    .string "the other side\n"
    .string "of the room\n"
    .string "a moment ago.$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "A game with\n"
    .string "MARIO wearing a\n"
    .string "bucket on his head.\p"
    .string "I played it\n"
    .string "for ten minutes.\p"
    .string "My mom says\n"
    .string "I was here\n"
    .string "for two days.$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "My Secrets!\n"
    .string "Skill: Mimicry!\n"
    .string "Hobby: Collecting dolls!\n"
    .string "Favorite Pokemon: Clefairy!\p"
    .string "New entry:\n"
    .string "I met Chronyx.\n"
    .string "It didn't stay long.\n"
    .string "Or maybe it did.$"
