Route16_House_Text_FoundMySecretRetreat::
    .string "I've been in\n"
    .string "this house for\p"
    .string "three days.\p"
    .string "Something circles outside\n"
    .string "at night.\p"
    .string "Take this and go.\p"
    .string "Fly away from here.$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} received HM02\n"
    .string "from the girl.$"

Route16_House_Text_ExplainHM02::
    .string "HM02 is FLY.\n"
    .string "It's a wonderfully convenient move.\p"
    .string "Please, put it to good use.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "You don't have any room for this.$"

Route16_House_Text_Fearow::
    .string "FEAROW: Kyueen!$"

