PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "This Tower was built\n"
    .string "for Pokemon that died.\p"
    .string "Something here was\n"
    .string "not built for them.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "Did you come\n"
    .string "to pay respects?\p"
    .string "Something else came\n"
    .string "here for a\n"
    .string "different reason.\p"
    .string "It's still here.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "Did you come\n"
    .string "to pay respects?\p"
    .string "Something else came\n"
    .string "here for a\n"
    .string "different reason.\p"
    .string "It's still here.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "I came to\n"
    .string "pray for my\n"
    .string "Clefairy.\p"
    .string "Sniff.\p"
    .string "Something prayed back.\p"
    .string "I don't know\n"
    .string "what it wanted.$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "My Growlithe.\p"
    .string "Why did you die?\p"
    .string "Something answered\n"
    .string "that question.\p"
    .string "I wish it hadn't.$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "I am a Channeler.\p"
    .string "The spirits above\n"
    .string "are not mischievous.\p"
    .string "They are frightened.$"
