CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .string "Hello!\n"
    .string "Welcome to Celadon\n"
    .string "Dept. Store.\p"
    .string "Store layout on\n"
    .string "the right.\p"
    .string "Please report any\n"
    .string "unusual marks on\n"
    .string "the floor to\n"
    .string "management.\p"
    .string "We've been finding them\n"
    .string "more frequently.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .string "1F: SERVICE COUNTER\p"
    .string "2F: TRAINER'S MARKET\p"
    .string "3F: TV GAME SHOP\p"
    .string "4F: WISE MAN GIFTS\p"
    .string "5F: DRUGSTORE\p"
    .string "ROOFTOP SQUARE: VENDING MACHINES$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .string "1F: SERVICE COUNTER$"

