VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .string "A trained Pokemon\n"
    .string "is stronger than\n"
    .string "a wild one.\p"
    .string "The sailors say\n"
    .string "there's something out\n"
    .string "there that wasn't\n"
    .string "trained by anyone.\p"
    .string "Older than training.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .string "My Pokemon was\n"
    .string "poisoned.\n"
    .string "It fainted walking.\p"
    .string "I found it\n"
    .string "near the harbor.\p"
    .string "Something frightened it\n"
    .string "there first.\p"
    .string "Then the poison.$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .string "No universally strong\n"
    .string "Pokemon exists.\p"
    .string "Every type has\n"
    .string "a weakness.\p"
    .string "The sailors described\n"
    .string "something with no\n"
    .string "weakness they could find.\p"
    .string "They stopped describing it.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .string "The urge to battle with someone\n"
    .string "you've tangled with before…\p"
    .string "Have you ever had that urge?\n"
    .string "I'm sure you have.\p"
    .string "I wanted to battle certain people\n"
    .string "again over and over, too.\p"
    .string "So, I've been giving these away.\n"
    .string "Please, take one!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .string "Use that device and you'll find\n"
    .string "TRAINERS looking for a rematch.\p"
    .string "You have to charge its battery to\n"
    .string "use it, though.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .string "How do you use the VS SEEKER?\n"
    .string "There's nothing to it.\p"
    .string "Use it like beep-beep-beep, and\n"
    .string "TRAINERS around you will notice.\p"
    .string "If any TRAINER wants a rematch,\n"
    .string "it will let you know immediately.\p"
    .string "Charge its battery and use it\n"
    .string "while you're on a road.$"
