VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "That's too bad.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

VermilionCity_House2_Text_ThankYou::
	.string "Thank you!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "Thank you!\n"
	.string "How is my\n"
	.string "old Spearow?\p"
	.string "My Farfetch'd DUX\n"
	.string "is doing great.\p"
	.string "DUX won't go\n"
	.string "outside at dusk.\p"
	.string "Just stands at\n"
	.string "the window.\n"
	.string "Looking up.$"
