CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "Getting a present\n"
    .string "for my girlfriend.\n"
    .string "A Poke Doll.\p"
    .string "She asked for\n"
    .string "something that keeps\n"
    .string "ProtoGlyph away.\p"
    .string "We don't sell that.\p"
    .string "The doll will\n"
    .string "have to do.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "A Poke Doll\n"
    .string "distracts wild Pokemon.\p"
    .string "ProtoGlyph is not\n"
    .string "distracted by dolls.\p"
    .string "Not distracted by\n"
    .string "anything we've tried.\p"
    .string "It just moves\n"
    .string "through.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "Express yourself with gifts!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution Special!\n"
    .string "Element STONES on sale now!$"
